### ISSUE TITLE
vagrant is not necessary on a Linux

### ISSUE THREAD

**Issue by MaxiReglisse** [gaieges/drupal-ansible-container#1]
hello,
thanks for this work around ansible-container, it works fine for me !
but i did not use vagrant, because docker is available on my laptop (ubuntu 16.04),
and i changed ports for apache : 
ports:
      - "8080:80"
instead of : 
ports:
      - "80:80"
this was necessary to launch my web browser on localhost:8080, in order to configure drupal : 
http://localhost:8080/drupal-8.1.3/core/install.php

Thank you again for this work.

**Comment by gaieges** [comment]
The point about Vagrant makes sense, I'm going to keep it in the repo for those that aren't in the same boat as you though.  I like to keep clean images and systems so I put everything in vagrant and off of my mac.

Looking at the readme vs code, it looks like there's a difference there which I'll fix. Thanks for flagging.
